"""
training_rl_agent.py

Main training script for the Adaptive Multi-hop Retrieval RL Agent.

Two-stage training pipeline
----------------------------
STAGE 1 — Imitation Learning
    Warm-up the policy using high-quality heuristic trajectories.
    These trajectories are generated by a simple BFS-ranked retriever
    that selects the top-scoring neighbour at each hop (teacher).

STAGE 2 — Reinforcement Learning (PPO)
    Fine-tune the policy via PPO with the multi-objective reward function.
    LLM judge provides weak supervision reward signal.

Usage
-----
    python training_rl_agent.py --stage both --iterations 100
    python training_rl_agent.py --stage rl   --iterations 200 --resume
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import random
import sys
from pathlib import Path
from typing import List, Optional

import torch

# ---------------------------------------------------------------------------
# Setup logging early
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
    ],
)
logger = logging.getLogger("training")


# ---------------------------------------------------------------------------
# Imports (after logging)
# ---------------------------------------------------------------------------
from src.config.settings import DEFAULT_CONFIG, Config
from src.kg.neo4j_connector import KGConnector
from src.retrieval.query_encoder import QueryEncoder
from src.retrieval.node_encoder import NodeEncoder
from src.retrieval.state_builder import StateBuilder
from src.retrieval.semantic_scorer import SemanticScorer
from src.retrieval.stopping import AdaptiveStoppingModule
from src.retrieval.adaptive_retriever import AdaptiveRetriever
from src.rl.kg_env import KGEnvironment
from src.rl.actor import Actor
from src.rl.critic import Critic
from src.rl.reward import RewardFunction
from src.rl.replay_buffer import RolloutBuffer, Transition
from src.rl.ppo_trainer import PPOTrainer, ImitationTrainer
from src.rl.checkpoint import CheckpointManager
from src.llm.llm_judge import LLMJudge, LLMSynthesiser
from src.reasoning.agent import ReasoningAgent
from src.data.qa_dataset import QAItem, load_qa_dataset, build_gold_map


# ---------------------------------------------------------------------------
# Default dataset locations (override via CLI)
# ---------------------------------------------------------------------------
DEFAULT_QA_TRAIN = "data/processed/qa_train.jsonl"
DEFAULT_QA_TEST = "data/processed/qa_test.jsonl"


# ---------------------------------------------------------------------------
# Heuristic teacher trajectory generator (Stage 1)
# ---------------------------------------------------------------------------

def generate_teacher_trajectories(
    env: KGEnvironment,
    actor: Actor,
    qa_items: List[QAItem],
    buffer: RolloutBuffer,
    n_episodes: int = 100,
    teacher_max_hops: int = 5,
) -> None:
    """
    Generate labelled trajectories with a gold-aware heuristic teacher.

    For each sampled QA item the teacher navigates the KG as follows, at each hop:
      1. If any reachable neighbour IS a gold product → move there (it knows the
         target, so it demonstrates navigating toward the answer).
      2. Otherwise → move to the neighbour most semantically similar to the query.
      3. Once a gold product has been reached → STOP (demonstrates the stopping
         behaviour the policy must learn).

    Every transition stores ``teacher_action_idx`` as the imitation label, and the
    episode carries gold_answers so the reward (logged per transition) is exact.
    """
    logger.info(
        "Generating %d teacher trajectories for imitation learning "
        "(dataset of %d queries)...",
        n_episodes, len(qa_items),
    )

    from torch.nn.functional import cosine_similarity

    n_success = 0
    n_reached_gold = 0
    _first_error_logged = False

    for ep_idx in range(n_episodes):
        item = random.choice(qa_items)
        gold_set = set(item.gold_answers)
        try:
            obs, info = env.reset(item.query, gold_answers=item.gold_answers)
            query_repr = info["query_repr"]
            query_emb = query_repr.embedding              # projected (for buffer)
            query_base = query_repr.base_embedding        # shared space (for scoring)
            buffer.start_episode()
            done = False
            hop = 0
            force_stop = False
            produced = False

            while not done and hop < teacher_max_hops:
                actions = env.get_valid_actions()
                if not actions:
                    break

                stop_idx = len(actions) - 1  # STOP is always last
                non_stop = [a for a in actions if not a.is_stop]

                if force_stop or not non_stop:
                    teacher_idx = stop_idx
                else:
                    # (1) prefer a neighbour that is itself a gold product
                    gold_actions = [
                        a for a in non_stop if a.target_node_id in gold_set
                    ]
                    if gold_actions:
                        teacher_idx = gold_actions[0].index
                    else:
                        # (2) highest semantic relevance to the query, computed
                        # in the shared base space (query_base vs node base).
                        best_idx = non_stop[0].index
                        best_score = -1.0
                        for a in non_stop:
                            if a.target_base_embedding is not None:
                                score = cosine_similarity(
                                    query_base.unsqueeze(0),
                                    a.target_base_embedding.unsqueeze(0),
                                ).item()
                                if score > best_score:
                                    best_score = score
                                    best_idx = a.index
                        teacher_idx = best_idx

                action_embs, _ = actor._stack_action_embeddings(actions)
                obs_next, reward, done, step_info = env.step(teacher_idx)

                transition = Transition(
                    state_vec=obs.detach().cpu(),
                    action_embs=action_embs.detach().cpu(),
                    query_emb=query_emb.detach().cpu(),
                    action_idx=teacher_idx,
                    log_prob=-1.0,     # placeholder for imitation
                    reward=reward,
                    value=0.0,
                    done=done,
                    teacher_action_idx=teacher_idx,   # label for imitation loss
                    hop=hop,
                    node_id=step_info.node_id,
                    node_type=step_info.node_type,
                    relation=step_info.relation_type,
                )
                buffer.add(transition)
                produced = True

                # (3) if we have just reached a gold product, stop next hop
                if step_info.node_id in gold_set:
                    n_reached_gold += 1
                    force_stop = True

                obs = obs_next
                hop += 1

            buffer.end_episode()
            if produced:
                n_success += 1
            if (ep_idx + 1) % 20 == 0:
                logger.info(
                    "  Teacher %d/%d | ok=%d reached_gold=%d buffer=%d",
                    ep_idx + 1, n_episodes, n_success, n_reached_gold, len(buffer),
                )

        except Exception as exc:
            if not _first_error_logged:
                logger.error(
                    "First teacher episode error (query=%r) — full traceback:",
                    item.query, exc_info=True,
                )
                _first_error_logged = True
            else:
                logger.warning("Teacher episode %d failed: %s", ep_idx, exc)
            continue

    logger.info(
        "Teacher trajectories generated: %d transitions, %d/%d episodes ok, "
        "%d gold products reached.",
        len(buffer), n_success, n_episodes, n_reached_gold,
    )


# ---------------------------------------------------------------------------
# Build system
# ---------------------------------------------------------------------------

def build_system(config: Config) -> dict:
    """Instantiate all components of the system."""
    logger.info("Building system components...")

    connector = KGConnector(config)
    if not connector.ping():
        raise ConnectionError("Cannot connect to Neo4j. Check NEO4J_URI/credentials.")

    query_enc = QueryEncoder(config)
    node_enc = NodeEncoder(config)
    state_builder = StateBuilder(config)
    scorer = SemanticScorer(mode="cosine", config=config)
    llm_judge = LLMJudge(config)
    reward_fn = RewardFunction(config, llm_judge=llm_judge)
    actor = Actor(config)
    critic = Critic(config)
    buffer = RolloutBuffer(config)

    env = KGEnvironment(
        connector=connector,
        query_enc=query_enc,
        node_enc=node_enc,
        state_builder=state_builder,
        scorer=scorer,
        reward_fn=reward_fn,
        config=config,
    )

    stopping = AdaptiveStoppingModule(config, policy_network=actor.policy)
    retriever = AdaptiveRetriever(env, actor, stopping, config)
    llm_synth = LLMSynthesiser(config)
    agent = ReasoningAgent(retriever, llm_synth, config)
    ckpt = CheckpointManager(config=config)

    logger.info(
        "System ready. Products in KG: %d",
        connector.get_node_count("Product"),
    )

    return {
        "connector": connector,
        "query_enc": query_enc,
        "node_enc": node_enc,
        "state_builder": state_builder,
        "scorer": scorer,
        "env": env,
        "actor": actor,
        "critic": critic,
        "buffer": buffer,
        "reward_fn": reward_fn,
        "stopping": stopping,
        "retriever": retriever,
        "agent": agent,
        "ckpt": ckpt,
        "llm_judge": llm_judge,
    }


# ---------------------------------------------------------------------------
# Stage 1: Imitation Learning
# ---------------------------------------------------------------------------

def run_stage1(
    components: dict,
    config: Config,
    qa_items: List[QAItem],
    n_teacher_episodes: int = 100,
) -> None:
    logger.info("=" * 60)
    logger.info("STAGE 1: Imitation Learning")
    logger.info("=" * 60)

    actor: Actor = components["actor"]
    env: KGEnvironment = components["env"]
    buffer: RolloutBuffer = components["buffer"]
    ckpt: CheckpointManager = components["ckpt"]
    connector: KGConnector = components["connector"]

    # --- Preflight: KG populated + gold answers actually exist in the graph ---
    n_products = connector.get_node_count("Product")
    logger.info("Preflight: Product nodes in KG = %d", n_products)
    if n_products == 0:
        raise RuntimeError(
            "KG has 0 Product nodes. Check NEO4J_URI/NEO4J_DATABASE and that "
            "Task-1 import completed."
        )

    sample = qa_items[: min(50, len(qa_items))]
    checked = found = 0
    for it in sample:
        for asin in it.gold_answers[:1]:   # check one gold per sampled item
            checked += 1
            props, _ = connector.get_node_by_id(asin)
            if props:
                found += 1
    rate = found / max(checked, 1)
    logger.info(
        "Preflight: gold-answer membership in KG = %d/%d (%.0f%%)",
        found, checked, 100 * rate,
    )
    if rate < 0.5:
        logger.warning(
            "More than half of sampled gold answers are NOT in the graph. "
            "qa_train.jsonl was likely generated against a different database "
            "or before the import. Regenerate it: "
            "python scripts/build_qa_dataset.py --total 3000"
        )

    buffer.clear()

    # Generate teacher trajectories from the real QA dataset
    generate_teacher_trajectories(
        env=env,
        actor=actor,
        qa_items=qa_items,
        buffer=buffer,
        n_episodes=n_teacher_episodes,
    )

    if len(buffer) == 0:
        raise RuntimeError(
            "Teacher produced 0 transitions — cannot run imitation. "
            "Check Neo4j connectivity and that qa_train.jsonl anchors resolve."
        )

    # Unfreeze query encoder projection for training
    components["query_enc"].unfreeze_projection()

    # Train imitation
    il_trainer = ImitationTrainer(
        actor=actor,
        buffer=buffer,
        config=config,
        checkpoint_manager=ckpt,
    )
    losses = il_trainer.train(n_epochs=config.imitation.epochs)

    # Save Stage 1 checkpoint
    import torch.optim as optim
    dummy_opt = optim.Adam(actor.get_parameters(), lr=1e-3)
    ckpt.save(
        model=actor.policy,
        optimiser=dummy_opt,
        step=0,
        metrics={"final_il_loss": losses[-1] if losses else 0.0},
        tag="imitation_final",
    )
    logger.info("Stage 1 complete. Final IL loss=%.4f", losses[-1] if losses else 0.0)

    # Clear buffer for Stage 2
    buffer.clear()


# ---------------------------------------------------------------------------
# Stage 2: PPO Reinforcement Learning
# ---------------------------------------------------------------------------

def run_stage2(
    components: dict,
    config: Config,
    qa_items: List[QAItem],
    n_iterations: int = 200,
    resume: bool = False,
) -> None:
    logger.info("=" * 60)
    logger.info("STAGE 2: PPO Reinforcement Learning")
    logger.info("=" * 60)

    actor: Actor = components["actor"]
    critic: Critic = components["critic"]
    env: KGEnvironment = components["env"]
    buffer: RolloutBuffer = components["buffer"]
    ckpt: CheckpointManager = components["ckpt"]

    queries = [it.query for it in qa_items]
    gold_map = build_gold_map(qa_items)

    # Resume from checkpoint if available
    if resume and ckpt.best_exists():
        import torch.optim as optim
        dummy_opt = optim.Adam(actor.get_parameters())
        meta = ckpt.load(
            model=actor.policy,
            optimiser=dummy_opt,
            tag="best",
            device=torch.device(config.encoder.device),
        )
        logger.info("Resumed from best checkpoint: %s", meta)

    ppo_trainer = PPOTrainer(
        actor=actor,
        critic=critic,
        env=env,
        buffer=buffer,
        config=config,
        checkpoint_manager=ckpt,
        gold_map=gold_map,
    )

    metrics = ppo_trainer.train(
        queries=queries,
        n_iterations=n_iterations,
    )

    # Save final metrics
    results_path = config.paths.results / "ppo_training_metrics.json"
    results_path.parent.mkdir(parents=True, exist_ok=True)
    with open(results_path, "w") as f:
        json.dump(metrics, f, indent=2)

    logger.info(
        "Stage 2 complete. Best reward=%.4f. Metrics saved to %s",
        ppo_trainer._best_reward, results_path,
    )


# ---------------------------------------------------------------------------
# Quick inference test
# ---------------------------------------------------------------------------

def run_inference_test(components: dict) -> None:
    logger.info("=" * 60)
    logger.info("INFERENCE TEST")
    logger.info("=" * 60)

    agent: ReasoningAgent = components["agent"]
    test_queries = [
        "laptop under 500 dollars with long battery life and lightweight",
        "wireless headphones with noise cancellation not too expensive",
        "smartphone great camera under 300",
    ]

    for q in test_queries:
        logger.info("Query: %s", q)
        try:
            answer = agent.answer(q, deterministic=True)
            logger.info("  Hops: %d | Uncertainty: %.3f | Stop: %s",
                        answer.n_hops, answer.uncertainty, answer.stop_reason)
            logger.info("  Evidence count: %d", len(answer.evidence_chain))
            logger.info("  Answer preview: %s", answer.final_answer[:200])
            logger.info("  Path: %s", answer.reasoning_path_text[:300])
        except Exception as exc:
            logger.warning("  Inference failed: %s", exc)
        logger.info("")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train Adaptive Multi-hop Retrieval RL Agent"
    )
    parser.add_argument(
        "--stage",
        choices=["imitation", "rl", "both"],
        default="both",
        help="Training stage to run",
    )
    parser.add_argument("--iterations", type=int, default=100,
                        help="PPO training iterations (Stage 2)")
    parser.add_argument("--teacher-episodes", type=int, default=100,
                        help="Teacher episodes for Stage 1")
    parser.add_argument("--resume", action="store_true",
                        help="Resume from latest checkpoint")
    parser.add_argument("--test", action="store_true",
                        help="Run inference test after training")
    parser.add_argument("--device", default="cpu",
                        help="Device: cpu or cuda")
    parser.add_argument("--qa-train", default=DEFAULT_QA_TRAIN,
                        help="Path to qa_train.jsonl")
    parser.add_argument("--qa-test", default=DEFAULT_QA_TEST,
                        help="Path to qa_test.jsonl (used for inference test)")
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Set seed
    random.seed(args.seed)
    torch.manual_seed(args.seed)

    # Override device in config
    config = DEFAULT_CONFIG
    config.encoder.device = args.device

    # Setup file logging
    config.paths.logs.mkdir(parents=True, exist_ok=True)
    fh = logging.FileHandler(config.paths.logs / "training.log")
    fh.setFormatter(logging.Formatter(
        "%(asctime)s %(levelname)s %(name)s — %(message)s"
    ))
    logging.getLogger().addHandler(fh)

    logger.info("Starting training — stage=%s device=%s seed=%d",
                args.stage, args.device, args.seed)

    # Build all components
    components = build_system(config)

    # Load the QA dataset (training queries + gold answers)
    qa_train = load_qa_dataset(args.qa_train, require_gold=True)
    logger.info("Training on %d QA samples from %s", len(qa_train), args.qa_train)

    try:
        if args.stage in ("imitation", "both"):
            run_stage1(
                components=components,
                config=config,
                qa_items=qa_train,
                n_teacher_episodes=args.teacher_episodes,
            )

        if args.stage in ("rl", "both"):
            run_stage2(
                components=components,
                config=config,
                qa_items=qa_train,
                n_iterations=args.iterations,
                resume=args.resume,
            )

        if args.test:
            run_inference_test(components)

    finally:
        components["connector"].close()
        logger.info("Training complete. Connector closed.")


if __name__ == "__main__":
    main()