"""
training_rl_agent.py

Main training script for the Adaptive Multi-hop Retrieval RL Agent.

Two-stage training pipeline
----------------------------
STAGE 1 — Imitation Learning
    Warm-up the policy using high-quality heuristic trajectories.
    These trajectories are generated by a simple BFS-ranked retriever
    that selects the top-scoring neighbour at each hop (teacher).

STAGE 2 — Reinforcement Learning (PPO)
    Fine-tune the policy via PPO with the multi-objective reward function.
    LLM judge provides weak supervision reward signal.

Usage
-----
    python training_rl_agent.py --stage both --iterations 100
    python training_rl_agent.py --stage rl   --iterations 200 --resume
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import random
import sys
from pathlib import Path
from typing import List, Optional

import torch

# ---------------------------------------------------------------------------
# Setup logging early
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
    ],
)
logger = logging.getLogger("training")


# ---------------------------------------------------------------------------
# Imports (after logging)
# ---------------------------------------------------------------------------
from src.config.settings import DEFAULT_CONFIG, Config
from src.kg.neo4j_connector import KGConnector
from src.retrieval.query_encoder import QueryEncoder
from src.retrieval.node_encoder import NodeEncoder
from src.retrieval.state_builder import StateBuilder
from src.retrieval.semantic_scorer import SemanticScorer
from src.retrieval.stopping import AdaptiveStoppingModule
from src.retrieval.adaptive_retriever import AdaptiveRetriever
from src.rl.kg_env import KGEnvironment
from src.rl.actor import Actor
from src.rl.critic import Critic
from src.rl.reward import RewardFunction
from src.rl.replay_buffer import RolloutBuffer, Transition
from src.rl.ppo_trainer import PPOTrainer, ImitationTrainer
from src.rl.checkpoint import CheckpointManager
from src.llm.llm_judge import LLMJudge, LLMSynthesiser
from src.reasoning.agent import ReasoningAgent


# ---------------------------------------------------------------------------
# Sample training queries (Electronics domain)
# ---------------------------------------------------------------------------
TRAINING_QUERIES: List[str] = [
    "laptop under 500 dollars with long battery life",
    "wireless headphones with good sound quality and noise cancellation",
    "smartphone with great camera and fast performance",
    "bluetooth speaker waterproof and durable",
    "gaming mouse with high DPI and ergonomic design",
    "mechanical keyboard with good tactile feedback",
    "tablet for reading and drawing under 300 dollars",
    "smartwatch with heart rate monitor and GPS",
    "USB-C charger fast charging reliable not fragile",
    "monitor 27 inch 4K good color accuracy",
    "laptop lightweight not too expensive good battery",
    "earbuds truly wireless long battery comfortable fit",
    "router fast wifi good range not expensive",
    "external hard drive portable fast reliable",
    "webcam 1080p good in low light for streaming",
    "phone charger cable durable not easily damaged",
    "laptop stand adjustable sturdy lightweight",
    "printer wireless good for home use affordable",
    "headset for gaming with good microphone",
    "power bank high capacity fast charging compact",
]


# ---------------------------------------------------------------------------
# Heuristic teacher trajectory generator (Stage 1)
# ---------------------------------------------------------------------------

def generate_teacher_trajectories(
    env: KGEnvironment,
    actor: Actor,
    queries: List[str],
    buffer: RolloutBuffer,
    n_episodes: int = 50,
) -> None:
    """
    Generate labelled trajectories by greedily following the highest
    relevance-scored neighbour at each step (teacher policy).

    The teacher always selects the neighbour most semantically similar
    to the query — this is not optimal but provides a reasonable warm start.
    """
    logger.info("Generating %d teacher trajectories for imitation learning...", n_episodes)

    for ep_idx in range(n_episodes):
        query = random.choice(queries)
        try:
            obs, info = env.reset(query)
            query_emb = info["query_repr"].embedding
            buffer.start_episode()
            done = False
            hop = 0

            while not done and hop < 5:   # teacher uses max 5 hops
                actions = env.get_valid_actions()
                if not actions:
                    break

                # Teacher: pick action with highest semantic relevance to query
                # (excluding STOP unless it's the only option)
                non_stop = [a for a in actions if not a.is_stop]
                if not non_stop:
                    teacher_idx = len(actions) - 1  # STOP
                else:
                    # Score each non-stop action
                    best_idx = 0
                    best_score = -1.0
                    for a in non_stop:
                        if a.action_embedding is not None:
                            # Use node part of action embedding (first node_dim dims)
                            node_dim = DEFAULT_CONFIG.encoder.node_feature_dim
                            node_emb = a.action_embedding[:node_dim]
                            from torch.nn.functional import cosine_similarity
                            score = cosine_similarity(
                                query_emb.unsqueeze(0),
                                node_emb.unsqueeze(0),
                            ).item()
                            if score > best_score:
                                best_score = score
                                best_idx = a.index
                    teacher_idx = best_idx

                # Execute teacher action
                action_embs, _ = actor._stack_action_embeddings(actions)
                obs_next, reward, done, step_info = env.step(teacher_idx)

                transition = Transition(
                    state_vec=obs.detach().cpu(),
                    action_embs=action_embs.detach().cpu(),
                    query_emb=query_emb.detach().cpu(),
                    action_idx=teacher_idx,
                    log_prob=-1.0,     # placeholder for imitation
                    reward=reward,
                    value=0.0,
                    done=done,
                    teacher_action_idx=teacher_idx,   # label for imitation loss
                    hop=hop,
                    node_id=step_info.node_id,
                    node_type=step_info.node_type,
                    relation=step_info.relation_type,
                )
                buffer.add(transition)
                obs = obs_next
                hop += 1

            buffer.end_episode()
            if (ep_idx + 1) % 10 == 0:
                logger.info("  Teacher episode %d/%d done.", ep_idx + 1, n_episodes)

        except Exception as exc:
            logger.warning("Teacher episode %d failed: %s", ep_idx, exc)
            continue

    logger.info(
        "Teacher trajectories generated: %d transitions in buffer.",
        len(buffer),
    )


# ---------------------------------------------------------------------------
# Build system
# ---------------------------------------------------------------------------

def build_system(config: Config) -> dict:
    """Instantiate all components of the system."""
    logger.info("Building system components...")

    connector = KGConnector(config)
    if not connector.ping():
        raise ConnectionError("Cannot connect to Neo4j. Check NEO4J_URI/credentials.")

    query_enc = QueryEncoder(config)
    node_enc = NodeEncoder(config)
    state_builder = StateBuilder(config)
    scorer = SemanticScorer(mode="cosine", config=config)
    llm_judge = LLMJudge(config)
    reward_fn = RewardFunction(config, llm_judge=llm_judge)
    actor = Actor(config)
    critic = Critic(config)
    buffer = RolloutBuffer(config)

    env = KGEnvironment(
        connector=connector,
        query_enc=query_enc,
        node_enc=node_enc,
        state_builder=state_builder,
        scorer=scorer,
        reward_fn=reward_fn,
        config=config,
    )

    stopping = AdaptiveStoppingModule(config, policy_network=actor.policy)
    retriever = AdaptiveRetriever(env, actor, stopping, config)
    llm_synth = LLMSynthesiser(config)
    agent = ReasoningAgent(retriever, llm_synth, config)
    ckpt = CheckpointManager(config=config)

    logger.info(
        "System ready. Products in KG: %d",
        connector.get_node_count("Product"),
    )

    return {
        "connector": connector,
        "query_enc": query_enc,
        "node_enc": node_enc,
        "state_builder": state_builder,
        "scorer": scorer,
        "env": env,
        "actor": actor,
        "critic": critic,
        "buffer": buffer,
        "reward_fn": reward_fn,
        "stopping": stopping,
        "retriever": retriever,
        "agent": agent,
        "ckpt": ckpt,
        "llm_judge": llm_judge,
    }


# ---------------------------------------------------------------------------
# Stage 1: Imitation Learning
# ---------------------------------------------------------------------------

def run_stage1(components: dict, config: Config, n_teacher_episodes: int = 100) -> None:
    logger.info("=" * 60)
    logger.info("STAGE 1: Imitation Learning")
    logger.info("=" * 60)

    actor: Actor = components["actor"]
    env: KGEnvironment = components["env"]
    buffer: RolloutBuffer = components["buffer"]
    ckpt: CheckpointManager = components["ckpt"]

    buffer.clear()

    # Generate teacher trajectories
    generate_teacher_trajectories(
        env=env,
        actor=actor,
        queries=TRAINING_QUERIES,
        buffer=buffer,
        n_episodes=n_teacher_episodes,
    )

    # Unfreeze query encoder projection for training
    components["query_enc"].unfreeze_projection()

    # Train imitation
    il_trainer = ImitationTrainer(
        actor=actor,
        buffer=buffer,
        config=config,
        checkpoint_manager=ckpt,
    )
    losses = il_trainer.train(n_epochs=config.imitation.epochs)

    # Save Stage 1 checkpoint
    import torch.optim as optim
    dummy_opt = optim.Adam(actor.get_parameters(), lr=1e-3)
    ckpt.save(
        model=actor.policy,
        optimiser=dummy_opt,
        step=0,
        metrics={"final_il_loss": losses[-1] if losses else 0.0},
        tag="imitation_final",
    )
    logger.info("Stage 1 complete. Final IL loss=%.4f", losses[-1] if losses else 0.0)

    # Clear buffer for Stage 2
    buffer.clear()


# ---------------------------------------------------------------------------
# Stage 2: PPO Reinforcement Learning
# ---------------------------------------------------------------------------

def run_stage2(
    components: dict,
    config: Config,
    n_iterations: int = 200,
    resume: bool = False,
) -> None:
    logger.info("=" * 60)
    logger.info("STAGE 2: PPO Reinforcement Learning")
    logger.info("=" * 60)

    actor: Actor = components["actor"]
    critic: Critic = components["critic"]
    env: KGEnvironment = components["env"]
    buffer: RolloutBuffer = components["buffer"]
    ckpt: CheckpointManager = components["ckpt"]

    # Resume from checkpoint if available
    if resume and ckpt.best_exists():
        import torch.optim as optim
        dummy_opt = optim.Adam(actor.get_parameters())
        meta = ckpt.load(
            model=actor.policy,
            optimiser=dummy_opt,
            tag="best",
            device=torch.device(config.encoder.device),
        )
        logger.info("Resumed from best checkpoint: %s", meta)

    ppo_trainer = PPOTrainer(
        actor=actor,
        critic=critic,
        env=env,
        buffer=buffer,
        config=config,
        checkpoint_manager=ckpt,
    )

    metrics = ppo_trainer.train(
        queries=TRAINING_QUERIES,
        n_iterations=n_iterations,
    )

    # Save final metrics
    results_path = config.paths.results / "ppo_training_metrics.json"
    results_path.parent.mkdir(parents=True, exist_ok=True)
    with open(results_path, "w") as f:
        json.dump(metrics, f, indent=2)

    logger.info(
        "Stage 2 complete. Best reward=%.4f. Metrics saved to %s",
        ppo_trainer._best_reward, results_path,
    )


# ---------------------------------------------------------------------------
# Quick inference test
# ---------------------------------------------------------------------------

def run_inference_test(components: dict) -> None:
    logger.info("=" * 60)
    logger.info("INFERENCE TEST")
    logger.info("=" * 60)

    agent: ReasoningAgent = components["agent"]
    test_queries = [
        "laptop under 500 dollars with long battery life and lightweight",
        "wireless headphones with noise cancellation not too expensive",
        "smartphone great camera under 300",
    ]

    for q in test_queries:
        logger.info("Query: %s", q)
        try:
            answer = agent.answer(q, deterministic=True)
            logger.info("  Hops: %d | Uncertainty: %.3f | Stop: %s",
                        answer.n_hops, answer.uncertainty, answer.stop_reason)
            logger.info("  Evidence count: %d", len(answer.evidence_chain))
            logger.info("  Answer preview: %s", answer.final_answer[:200])
            logger.info("  Path: %s", answer.reasoning_path_text[:300])
        except Exception as exc:
            logger.warning("  Inference failed: %s", exc)
        logger.info("")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train Adaptive Multi-hop Retrieval RL Agent"
    )
    parser.add_argument(
        "--stage",
        choices=["imitation", "rl", "both"],
        default="both",
        help="Training stage to run",
    )
    parser.add_argument("--iterations", type=int, default=100,
                        help="PPO training iterations (Stage 2)")
    parser.add_argument("--teacher-episodes", type=int, default=100,
                        help="Teacher episodes for Stage 1")
    parser.add_argument("--resume", action="store_true",
                        help="Resume from latest checkpoint")
    parser.add_argument("--test", action="store_true",
                        help="Run inference test after training")
    parser.add_argument("--device", default="cpu",
                        help="Device: cpu or cuda")
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Set seed
    random.seed(args.seed)
    torch.manual_seed(args.seed)

    # Override device in config
    config = DEFAULT_CONFIG
    config.encoder.device = args.device

    # Setup file logging
    config.paths.logs.mkdir(parents=True, exist_ok=True)
    fh = logging.FileHandler(config.paths.logs / "training.log")
    fh.setFormatter(logging.Formatter(
        "%(asctime)s %(levelname)s %(name)s — %(message)s"
    ))
    logging.getLogger().addHandler(fh)

    logger.info("Starting training — stage=%s device=%s seed=%d",
                args.stage, args.device, args.seed)

    # Build all components
    components = build_system(config)

    try:
        if args.stage in ("imitation", "both"):
            run_stage1(
                components=components,
                config=config,
                n_teacher_episodes=args.teacher_episodes,
            )

        if args.stage in ("rl", "both"):
            run_stage2(
                components=components,
                config=config,
                n_iterations=args.iterations,
                resume=args.resume,
            )

        if args.test:
            run_inference_test(components)

    finally:
        components["connector"].close()
        logger.info("Training complete. Connector closed.")


if __name__ == "__main__":
    main()